### ISSUE TITLE
请问滚动条的颜色怎么修改？

### ISSUE THREAD

**Issue by xingyuzhang1949** [jhildenbiddle/typora-themeable#13]

**Comment by ReykerBlack** [comment]
**Example**

`themeable-dark.user.css`:

```css
/* Scrollbar */
::-webkit-scrollbar-thumb {
  background: #3b82f67f;
}

::-webkit-scrollbar-thumb:hover {
  background: #3b82f6bf;
}

::-webkit-scrollbar-thumb:active {
  background: #3b82f6ff;
}
```
